### ISSUE TITLE
Be able to edit/delete post if posted by the logged in user

### ISSUE THREAD

**Issue by georgeglessner** [georgeglessner/HeapExchange#8]

**Comment by lefflerl** [comment]
Code works, but when editing posts it updates the post field in firebase but doesn't show it in the table on our website unless it is refreshed.

**Comment by georgeglessner** [comment]
@lefflerl I think you need to add child_changed event.

> The child_changed event is triggered any time a child node is modified. This includes any modifications to descendants of the child node. It is typically used in conjunction with child_added and child_removed to respond to changes to a list of items. The snapshot passed to the event callback contains the updated data for the child.

**Comment by lefflerl** [comment]
@georgeglessner Got the logic to work, and changes have been implemented. Buttons still need to be added to the class to look nice. Let me know if you find any errors with the buttons.

**Comment by lefflerl** [comment]
Just realized that I still need to copy this functionality to a few other pages. Will do tomorrow.
